import OpenAI from 'openai';

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

function toBase64(str) {
	return Buffer.from(str, 'utf8').toString('base64');
}

function isAuthorized(req) {
	if (process.env.NODE_ENV !== 'production') return true;
	// Allow scheduled runs
	if (req.headers['x-vercel-cron']) return true;
	// Allow logged-in site users
	const cookieAuth = req.cookies?.site_auth === '1' || req.cookies?.get?.('site_auth')?.value === '1';
	if (cookieAuth) return true;
	// Allow manual trigger with CRON_SECRET
	const provided = (req.query && req.query.secret) || (req.body && req.body.secret);
	if (provided && process.env.CRON_SECRET && provided === process.env.CRON_SECRET) return true;
	return false;
}

function formatDateSlug() {
	const tz = 'America/New_York';
	const d = new Date();
	const y = new Intl.DateTimeFormat('en-CA', { timeZone: tz, year: 'numeric' }).format(d);
	const m = new Intl.DateTimeFormat('en-CA', { timeZone: tz, month: '2-digit' }).format(d);
	const day = new Intl.DateTimeFormat('en-CA', { timeZone: tz, day: '2-digit' }).format(d);
	return `${y}-${m}-${day}`;
}

function formatTimeSlug() {
	const tz = 'America/New_York';
	const d = new Date();
	const hh = new Intl.DateTimeFormat('en-GB', { timeZone: tz, hour: '2-digit', hour12: false }).format(d);
	const mm = new Intl.DateTimeFormat('en-GB', { timeZone: tz, minute: '2-digit' }).format(d);
	const ss = new Intl.DateTimeFormat('en-GB', { timeZone: tz, second: '2-digit' }).format(d);
	return `${hh}${mm}${ss}`; // HHMMSS
}

function sanitizeSlug(text) {
	return text.toLowerCase().replace(/[^a-z0-9\s-]/g, '').trim().replace(/\s+/g, '-').replace(/-+/g, '-');
}

async function generateSeoPost(seed) {
	const prompt = `You are an expert copywriter for a carpet installation company.
Write a unique 600–800 word SEO-friendly blog post with the following requirements:

Use a fresh, distinctive H1 title focused on carpet installation tips (make sure it doesn’t repeat common phrases).

Organize content with H2 sections for main tips and optional H3 subsections for deeper details.

Naturally include these keywords throughout the article: carpet installation, padding, subfloor, seams, stretching, professional installer, DIY.

Maintain a friendly, approachable, and trustworthy tone suitable for homeowners.

Provide practical, actionable advice with clear examples or step-by-step insights.

End with a concise call-to-action encouraging readers to contact a local professional for help.

Ensure the content feels fresh, original, and structured differently from standard carpet installation blogs. Use the uniqueness seed: ${seed} to guarantee variation in topic angle, structure, and phrasing.

Output should be valid HTML using <h1>, <h2>, <h3>, <p>, and <ul>/<li> tags when appropriate.`;
	const response = await openai.chat.completions.create({
		model: 'gpt-4o-mini',
		messages: [
			{ role: 'system', content: 'Produce clean, semantic HTML only. No markdown.' },
			{ role: 'user', content: prompt }
		],
		temperature: 0.8,
		max_tokens: 1200
	});
	const html = response.choices?.[0]?.message?.content?.trim();
	if (!html) throw new Error('No content generated by OpenAI');
	const titleMatch = html.match(/<h1[^>]*>(.*?)<\/h1>/i);
	const title = titleMatch ? titleMatch[1].replace(/<[^>]+>/g, '').trim() : 'Carpet Installation Tips You Can Trust';
	return { title, content: html };
}

async function generateImagePrompt(title) {
	return `Photo-realistic, well-lit image illustrating ${title.toLowerCase()} — tools (knee kicker, carpet stretcher), padding and subfloor preparation, clean aesthetic, professional style. No text overlay.`;
}

async function generateImageB64(title) {
	const prompt = await generateImagePrompt(title);
	const result = await openai.images.generate({ model: 'gpt-image-1', prompt, size: '1024x1024', quality: 'high' });
	const b64 = result.data?.[0]?.b64_json;
	if (!b64) throw new Error('No image generated by OpenAI');
	return Buffer.from(b64, 'base64');
}

async function wpFetch(path, options = {}) {
	const baseUrl = process.env.WP_API_URL || '';
	if (!baseUrl) throw new Error('WP_API_URL not configured');
	const url = baseUrl.replace(/\/$/, '') + path;
	const authHeader = 'Basic ' + toBase64(`${process.env.WP_USER}:${process.env.WP_PASS}`);
	return fetch(url, { ...options, headers: { 'Authorization': authHeader, ...(options.headers || {}) } });
}

async function ensureNotDuplicate(slug) {
	const res = await wpFetch(`/posts?slug=${encodeURIComponent(slug)}&per_page=1`, { method: 'GET' });
	if (!res.ok) throw new Error(`WP slug check error ${res.status}: ${await res.text()}`);
	const arr = await res.json();
	if (Array.isArray(arr) && arr.length > 0) return { exists: true, post: { id: arr[0].id, link: arr[0].link || arr[0].guid?.rendered } };
	return { exists: false };
}

async function uploadFeaturedImage(buffer, filename = 'carpet-installation.png') {
	const res = await wpFetch('/media', { method: 'POST', headers: { 'Content-Type': 'image/png', 'Content-Disposition': `attachment; filename="${filename}"` }, body: buffer });
	if (!res.ok) throw new Error(`WP media upload error ${res.status}: ${await res.text()}`);
	const media = await res.json();
	return { id: media.id, url: media.source_url };
}

async function postToWordPress({ title, content, slug, featuredMediaId }) {
	const body = { title, content, status: 'publish', slug };
	if (featuredMediaId) body.featured_media = featuredMediaId;
	const res = await wpFetch('/posts', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
	if (!res.ok) throw new Error(`WP error ${res.status}: ${await res.text()}`);
	const data = await res.json();
	return { id: data.id, link: data.link || data.guid?.rendered };
}

export default async function handler(req, res) {
	if (req.method !== 'GET' && req.method !== 'POST') {
		return res.status(405).json({ error: 'Method Not Allowed' });
	}
	try {
		if (!isAuthorized(req)) {
			return res.status(401).json({ error: 'Unauthorized' });
		}

		const isCron = Boolean(req.headers['x-vercel-cron']);
		const force = req.method === 'GET' ? req.query?.force === '1' : Boolean(req.body?.force);
		const seed = new Date().toISOString();

		const post = await generateSeoPost(seed);
		const dateSlug = formatDateSlug();
		const timeSlug = formatTimeSlug();

		// Cron uses stable daily slug; manual always uses unique slug with time
		const baseDailySlug = sanitizeSlug(`carpet-installation-tips-${dateSlug}`);
		let finalSlug = isCron && !force ? baseDailySlug : `${baseDailySlug}-${timeSlug}`;

		if (isCron && !force) {
			const dupe = await ensureNotDuplicate(baseDailySlug);
			if (dupe.exists) {
				finalSlug = `${baseDailySlug}-cron-${timeSlug}`;
			}
		}

		let featuredMediaId = undefined, imageUrl = undefined;
		try {
			const imageBuffer = await generateImageB64(post.title);
			const uploaded = await uploadFeaturedImage(imageBuffer, `carpet-tips-${dateSlug}-${timeSlug}.png`);
			featuredMediaId = uploaded.id; imageUrl = uploaded.url;
		} catch (_) {}
		let contentWithImage = post.content;
		if (imageUrl) contentWithImage = contentWithImage.replace(/<h1[^>]*>.*?<\/h1>/i, (m) => `${m}\n<p><img src="${imageUrl}" alt="${post.title}" style="max-width:100%;height:auto;border-radius:8px" /></p>`);
		const wp = await postToWordPress({ title: post.title, content: contentWithImage, slug: finalSlug, featuredMediaId });
		return res.status(200).json({ success: true, ...wp, cron: isCron, forced: !isCron || force });
	} catch (err) {
		return res.status(500).json({ error: err.message || 'Internal Server Error' });
	}
}
