import OpenAI from 'openai';

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

function toBase64(str) {
	return Buffer.from(str, 'utf8').toString('base64');
}

function isAuthorized(req) {
	// Allow all requests in non-production for local development
	if (process.env.NODE_ENV !== 'production') return true;

	// Allow Vercel Cron invocations (Vercel sets this header on scheduled runs)
	const vercelCronHeader = req.headers['x-vercel-cron'];
	if (vercelCronHeader) return true;

	// Allow authenticated site users (logged in via SITE_PASSWORD)
	const cookieAuth = req.cookies?.site_auth === '1' || req.cookies?.get?.('site_auth')?.value === '1';
	if (cookieAuth) return true;

	// Fallback: allow with shared secret when provided explicitly (for manual triggers)
	const secretFromEnv = process.env.SECRET_KEY;
	const secretFromQuery = (req.query && req.query.secret) || (req.body && req.body.secret);
	if (secretFromEnv && secretFromQuery === secretFromEnv) return true;

	return false;
}

function formatDateSlug() {
	// Use America/New_York to align with Eastern time uniqueness
	const tz = 'America/New_York';
	const d = new Date();
	const y = new Intl.DateTimeFormat('en-CA', { timeZone: tz, year: 'numeric' }).format(d);
	const m = new Intl.DateTimeFormat('en-CA', { timeZone: tz, month: '2-digit' }).format(d);
	const day = new Intl.DateTimeFormat('en-CA', { timeZone: tz, day: '2-digit' }).format(d);
	return `${y}-${m}-${day}`; // YYYY-MM-DD
}

function sanitizeSlug(text) {
	return text
		.toLowerCase()
		.replace(/[^a-z0-9\s-]/g, '')
		.trim()
		.replace(/\s+/g, '-')
		.replace(/-+/g, '-');
}

async function generateSeoPost() {
	const prompt = `You are an expert copywriter for a carpet installation company.
Write a single 600-800 word SEO-friendly blog post with:
- A compelling H1 title about carpet installation tips
- Multiple H2 sections with actionable tips
- Optional H3 subsections for details
- Include keywords naturally: carpet installation, padding, subfloor, seams, stretching, professional installer, DIY
- Use a friendly, trustworthy tone
- End with a short call-to-action for contacting a local professional
Return valid HTML with <h1>, <h2>, <h3>, <p>, and <ul>/<li> when appropriate.`;

	const response = await openai.chat.completions.create({
		model: 'gpt-4o-mini',
		messages: [
			{ role: 'system', content: 'Produce clean, semantic HTML only. No markdown.' },
			{ role: 'user', content: prompt }
		],
		temperature: 0.7,
		max_tokens: 1200
	});

	const html = response.choices?.[0]?.message?.content?.trim();
	if (!html) throw new Error('No content generated by OpenAI');

	// Extract title from first <h1>
	const titleMatch = html.match(/<h1[^>]*>(.*?)<\/h1>/i);
	const title = titleMatch ? titleMatch[1].replace(/<[^>]+>/g, '').trim() : 'Carpet Installation Tips You Can Trust';
	return { title, content: html };
}

async function generateImagePrompt(title) {
	return `Photo-realistic, well-lit image illustrating ${title.toLowerCase()} — tools (knee kicker, carpet stretcher), padding and subfloor preparation, clean aesthetic, professional style. No text overlay.`;
}

async function generateImageB64(title) {
	const prompt = await generateImagePrompt(title);
	const result = await openai.images.generate({
		model: 'gpt-image-1',
		prompt,
		size: '1024x1024',
		quality: 'high'
	});
	const b64 = result.data?.[0]?.b64_json;
	if (!b64) throw new Error('No image generated by OpenAI');
	return Buffer.from(b64, 'base64');
}

async function wpFetch(path, options = {}) {
	const baseUrl = process.env.WP_API_URL || '';
	if (!baseUrl) throw new Error('WP_API_URL not configured');
	const url = baseUrl.replace(/\/$/, '') + path;
	const authHeader = 'Basic ' + toBase64(`${process.env.WP_USER}:${process.env.WP_PASS}`);
	return fetch(url, {
		...options,
		headers: {
			'Authorization': authHeader,
			...(options.headers || {})
		}
	});
}

async function ensureNotDuplicate(slug) {
	const res = await wpFetch(`/posts?slug=${encodeURIComponent(slug)}&per_page=1`, { method: 'GET' });
	if (!res.ok) {
		const text = await res.text();
		throw new Error(`WP slug check error ${res.status}: ${text}`);
	}
	const arr = await res.json();
	if (Array.isArray(arr) && arr.length > 0) {
		return { exists: true, post: { id: arr[0].id, link: arr[0].link || arr[0].guid?.rendered } };
	}
	return { exists: false };
}

async function uploadFeaturedImage(buffer, filename = 'carpet-installation.png') {
	const res = await wpFetch('/media', {
		method: 'POST',
		headers: {
			'Content-Type': 'image/png',
			'Content-Disposition': `attachment; filename="${filename}"`
		},
		body: buffer
	});
	if (!res.ok) {
		const text = await res.text();
		throw new Error(`WP media upload error ${res.status}: ${text}`);
	}
	const media = await res.json();
	return { id: media.id, url: media.source_url };
}

async function postToWordPress({ title, content, slug, featuredMediaId }) {
	const body = {
		title,
		content,
		status: 'publish',
		slug
	};
	if (featuredMediaId) body.featured_media = featuredMediaId;

	const res = await wpFetch('/posts', {
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		body: JSON.stringify(body)
	});

	if (!res.ok) {
		const text = await res.text();
		throw new Error(`WP error ${res.status}: ${text}`);
	}
	const data = await res.json();
	return { id: data.id, link: data.link || data.guid?.rendered };
}

export default async function handler(req, res) {
	try {
		if (!isAuthorized(req)) {
			return res.status(401).json({ error: 'Unauthorized' });
		}

		// 1) Generate the post content
		const post = await generateSeoPost();

		// 2) Prepare a deterministic daily slug to avoid duplicates
		const dateSlug = formatDateSlug();
		const baseSlug = sanitizeSlug(`carpet-installation-tips-${dateSlug}`);
		const dupe = await ensureNotDuplicate(baseSlug);
		if (dupe.exists) {
			return res.status(200).json({ success: true, duplicate: true, ...dupe.post });
		}

		// 3) Generate an image and upload to WordPress
		let featuredMediaId = undefined;
		let imageUrl = undefined;
		try {
			const imageBuffer = await generateImageB64(post.title);
			const uploaded = await uploadFeaturedImage(imageBuffer, `carpet-tips-${dateSlug}.png`);
			featuredMediaId = uploaded.id;
			imageUrl = uploaded.url;
		} catch (e) {
			// If image fails, continue without blocking the post
			imageUrl = undefined;
		}

		// 4) Optionally inject the image at the top of the content
		let contentWithImage = post.content;
		if (imageUrl) {
			contentWithImage = contentWithImage.replace(/<h1[^>]*>.*?<\/h1>/i, (match) => `${match}\n<p><img src="${imageUrl}" alt="${post.title}" style="max-width:100%;height:auto;border-radius:8px" /></p>`);
		}

		// 5) Create the post on WordPress
		const wp = await postToWordPress({ title: post.title, content: contentWithImage, slug: baseSlug, featuredMediaId });
		return res.status(200).json({ success: true, ...wp });
	} catch (err) {
		return res.status(500).json({ error: err.message });
	}
}
