import OpenAI from "openai";

let _openai = null;
function getOpenAI() {
  if (!_openai) {
    if (!process.env.OPENAI_API_KEY) {
      throw new Error("OPENAI_API_KEY environment variable is not set");
    }
    _openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  }
  return _openai;
}

function toBase64(str) {
  return Buffer.from(str, "utf8").toString("base64");
}

const CRON_SECRET = process.env.CRON_SECRET || "mySuperSecretKey";

function hasCronHeader(req) {
  const h = req.headers || {};
  const val = h["x-vercel-cron"] ?? h["x-vercel-schedule"];
  if (Array.isArray(val)) return val.length > 0 && Boolean(val[0]);
  return typeof val !== "undefined" && String(val).length > 0;
}

function isAuthorized(req) {
  // Always allow in development mode
  if (process.env.NODE_ENV !== "production") return true;
  // If a secret is provided, it MUST match the hardcoded value
  const provided =
    (req.query && req.query.secret) || (req.body && req.body.secret);
  if (typeof provided !== "undefined") {
    return provided === CRON_SECRET;
  }
  // Otherwise allow scheduled runs via Vercel header
  if (hasCronHeader(req)) return true;
  // Or allow logged-in site users via cookie
  const cookieAuth =
    req.cookies?.site_auth === "1" ||
    req.cookies?.get?.("site_auth")?.value === "1";
  if (cookieAuth) return true;
  return false;
}

function formatDateSlug() {
  const tz = "America/New_York";
  const d = new Date();
  const y = new Intl.DateTimeFormat("en-CA", {
    timeZone: tz,
    year: "numeric",
  }).format(d);
  const m = new Intl.DateTimeFormat("en-CA", {
    timeZone: tz,
    month: "2-digit",
  }).format(d);
  const day = new Intl.DateTimeFormat("en-CA", {
    timeZone: tz,
    day: "2-digit",
  }).format(d);
  return `${y}-${m}-${day}`;
}

function formatTimeSlug() {
  const tz = "America/New_York";
  const d = new Date();
  const hh = new Intl.DateTimeFormat("en-GB", {
    timeZone: tz,
    hour: "2-digit",
    hour12: false,
  }).format(d);
  const mm = new Intl.DateTimeFormat("en-GB", {
    timeZone: tz,
    minute: "2-digit",
  }).format(d);
  const ss = new Intl.DateTimeFormat("en-GB", {
    timeZone: tz,
    second: "2-digit",
  }).format(d);
  return `${hh}${mm}${ss}`; // HHMMSS
}

function sanitizeSlug(text) {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .trim()
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-");
}

async function generateSeoPost(seed) {
  console.log("  🤖 Calling OpenAI API for blog post generation...");
  const prompt = `SEO blog post for a personalized/custom song website. Seed: ${seed}.
Requirements:
- Unique H1 title, H2 sections, H3 where useful
- Emotional, narrative style; 700–900 words
- Weave in naturally: "make a song for me", "personalized song", "custom song", "song for [occasion]"
- End with a heartfelt CTA to request a custom song
- Output clean semantic HTML only (<h1><h2><h3><p><ul><li>). No markdown.`;
  const response = await getOpenAI().chat.completions.create({
    model: "gpt-4o-mini",
    messages: [{ role: "user", content: prompt }],
    temperature: 0.8,
    max_tokens: 1100,
  });
  const html = response.choices?.[0]?.message?.content?.trim();
  console.log("  ✅ OpenAI response received");
  if (!html) throw new Error("No content generated by OpenAI");
  const titleMatch = html.match(/<h1[^>]*>(.*?)<\/h1>/i);
  const title = titleMatch
    ? titleMatch[1].replace(/<[^>]+>/g, "").trim()
    : "Why a Personalized Song Is the Perfect Gift";
  // Strip the <h1> from content so title, image, and body are fully separate in WP
  const content = html.replace(/<h1[^>]*>.*?<\/h1>/i, "").trim();
  console.log("  📝 Extracted title:", title);
  return { title, content };
}

async function generateImagePrompt(title) {
  const occasions = [
    "birthday celebration",
    "wedding anniversary",
    "mother's day tribute",
    "romantic proposal",
    "graduation milestone",
    "long-distance love",
    "grief and remembrance",
    "friendship appreciation",
    "new baby arrival",
    "retirement send-off",
  ];
  const settings = [
    "cozy bedroom studio with fairy lights",
    "sunlit living room with a grand piano",
    "rustic cabin with a fireplace",
    "rooftop at golden hour",
    "beach at sunset",
    "intimate coffee shop corner",
    "lush garden with string lights",
    "modern recording studio with city view",
  ];
  const styles = [
    "cinematic film photography",
    "warm golden-hour editorial",
    "soft bokeh portrait style",
    "moody candlelight atmosphere",
    "vibrant lifestyle photography",
    "intimate documentary style",
  ];
  const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];
  const occasion = pick(occasions);
  const setting = pick(settings);
  const style = pick(styles);
  return `${style} image illustrating "${title}". Scene: ${setting}, evoking a ${occasion}. A musician or songwriter captures pure emotion — handwritten lyrics visible, instrument in hand, genuine feeling on their face. Warm, human, authentic. No text overlay, no logos.`;
}

async function generateImageB64(title) {
  const prompt = await generateImagePrompt(title);
  const result = await getOpenAI().images.generate({
    model: "gpt-image-1",
    prompt,
    size: "1024x1024",
    quality: "low",
  });
  const b64 = result.data?.[0]?.b64_json;
  if (!b64) throw new Error("No image generated by OpenAI");
  return Buffer.from(b64, "base64");
}

async function wpFetch(path, options = {}) {
  const baseUrl = process.env.WP_API_URL || "";
  if (!baseUrl) throw new Error("WP_API_URL not configured");
  const url = baseUrl.replace(/\/$/, "") + path;
  const authHeader =
    "Basic " + toBase64(`${process.env.WP_USER}:${process.env.WP_PASS}`);

  // Extract the origin from the WP_API_URL (e.g., https://bestcarpetinstallersnearme.com)
  const origin = baseUrl.replace(/\/wp-json.*$/, "");

  const headers = {
    Authorization: authHeader,
    "User-Agent":
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36",
    Accept: "application/json",
    "Accept-Language": "en-US,en;q=0.9",
    "Cache-Control": "no-cache",
    Pragma: "no-cache",
    Referer: origin + "/",
    Origin: origin,
    "X-Requested-With": "XMLHttpRequest",
    ...(options.headers || {}),
  };

  return fetch(url, {
    ...options,
    headers,
  });
}

async function ensureNotDuplicate(slug) {
  const res = await wpFetch(
    `/posts?slug=${encodeURIComponent(slug)}&per_page=1`,
    { method: "GET" },
  );
  if (!res.ok)
    throw new Error(`WP slug check error ${res.status}: ${await res.text()}`);
  const arr = await res.json();
  if (Array.isArray(arr) && arr.length > 0)
    return {
      exists: true,
      post: { id: arr[0].id, link: arr[0].link || arr[0].guid?.rendered },
    };
  return { exists: false };
}

async function uploadFeaturedImage(
  buffer,
  filename = "carpet-installation.png",
) {
  const res = await wpFetch("/media", {
    method: "POST",
    headers: {
      "Content-Type": "image/png",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
    body: buffer,
  });
  if (!res.ok)
    throw new Error(`WP media upload error ${res.status}: ${await res.text()}`);
  const media = await res.json();
  return { id: media.id, url: media.source_url };
}

async function postToWordPress({ title, content, slug, featuredMediaId }) {
  const body = { title, content, status: "publish", slug };
  if (featuredMediaId) body.featured_media = featuredMediaId;
  const res = await wpFetch("/posts", {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify(body),
  });
  if (!res.ok) throw new Error(`WP error ${res.status}: ${await res.text()}`);
  const data = await res.json();
  return { id: data.id, link: data.link || data.guid?.rendered };
}

export default async function handler(req, res) {
  console.log("🚀 [postBlog] Handler started");
  console.log("📝 Method:", req.method);

  if (req.method !== "GET" && req.method !== "POST") {
    console.log("❌ Invalid method");
    return res.status(405).json({ error: "Method Not Allowed" });
  }
  try {
    console.log("🔐 Checking authorization...");
    console.log("   NODE_ENV:", process.env.NODE_ENV);
    if (!isAuthorized(req)) {
      console.log("❌ Unauthorized");
      return res.status(401).json({ error: "Unauthorized" });
    }
    console.log("✅ Authorized");

    const isCron = hasCronHeader(req);
    const force =
      req.method === "GET"
        ? req.query?.force === "1"
        : Boolean(req.body?.force);
    const seed =
      formatDateSlug() + "-" + Math.random().toString(36).slice(2, 7);

    console.log("⚙️ Config:", { isCron, force, seed });

    console.log("📝 Generating blog post...");
    const post = await generateSeoPost(seed);
    console.log("✅ Post generated:", post.title);
    const dateSlug = formatDateSlug();
    const timeSlug = formatTimeSlug();
    console.log("🏷️ Slugs:", { dateSlug, timeSlug });

    // Cron uses stable daily slug; manual always uses unique slug with time
    const baseDailySlug = sanitizeSlug(`personalized-song-ideas-${dateSlug}`);
    let finalSlug =
      isCron && !force ? baseDailySlug : `${baseDailySlug}-${timeSlug}`;
    console.log("🔗 Base slug:", finalSlug);

    if (isCron && !force) {
      console.log("🔍 Checking for duplicate...");
      const dupe = await ensureNotDuplicate(baseDailySlug);
      if (dupe.exists) {
        console.log("⚠️ Duplicate found, adjusting slug");
        finalSlug = `${baseDailySlug}-cron-${timeSlug}`;
      } else {
        console.log("✅ No duplicate found");
      }
    }

    let featuredMediaId = undefined,
      imageUrl = undefined;
    try {
      console.log("🖼️ Generating featured image...");
      const imageBuffer = await generateImageB64(post.title);
      console.log("✅ Image generated, uploading to WP...");
      const uploaded = await uploadFeaturedImage(
        imageBuffer,
        `custom-song-${dateSlug}-${timeSlug}.png`,
      );
      featuredMediaId = uploaded.id;
      imageUrl = uploaded.url;
      console.log("✅ Image uploaded:", imageUrl);
    } catch (err) {
      console.log("⚠️ Image generation/upload failed:", err.message);
    }
    console.log("📤 Posting to WordPress...");
    const wp = await postToWordPress({
      title: post.title,
      content: post.content,
      slug: finalSlug,
      featuredMediaId,
    });
    console.log("✅ Successfully posted to WordPress!");
    console.log("🔗 Post URL:", wp.link);

    return res
      .status(200)
      .json({ success: true, ...wp, cron: isCron, forced: !isCron || force });
  } catch (err) {
    console.error("❌ ERROR:", err.message);
    console.error("Stack:", err.stack);
    return res
      .status(500)
      .json({ error: err.message || "Internal Server Error" });
  }
}
